apps/articles/urls.py
from django.urls import path

from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleByCategoryListView,
    ArticleByTagListView,
)

app_name = "articles"

# article details urls possible variants:
# /<pk>/ - show by id
# /<slug>/ - show by slug
# /<year>/<month>/<day>/<slug>/ - show by slug and puublication date

urlpatterns = [
    path(
        "by-category/<slug:slug>/",
        ArticleByCategoryListView.as_view(),
        name="by-category",
    ),
    path("by-tag/<slug>/", ArticleByTagListView.as_view(), name="by-tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        ArticleDetailView.as_view(),
        name="detail",
    ),
    path("", ArticleListView.as_view(), name="list"),  # url name: articles:list
]

newspaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("apps.pages.urls")),
    path("articles/", include("apps.articles.urls")),
    path("accounts/", include("apps.users.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/articles/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django_extensions.db.fields import AutoSlugField
from slugify import slugify
from taggit.managers import TaggableManager
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class Category(models.Model):
    name = models.CharField(_("name"), max_length=100)
    slug = AutoSlugField(populate_from="name", unique=True, slugify_function=slugify)
    image = models.ImageField(
        _("image"), max_length=300, upload_to="categories/images", blank=True, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)
        verbose_name = _("category")
        verbose_name_plural = _("categories")

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        return "<Category id={} name={} slug={} created_at={}>".format(
            self.pk, self.name, self.slug, self.created_at
        )

    def get_absolute_url(self):
        return reverse("articles:by-category", kwargs={"slug": self.slug})


class PublishedArticlesManager(models.Manager):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(published_at__isnull=False)
            .order_by("-published_at")
        )


class Article(models.Model):
    category = models.ForeignKey(
        Category,
        verbose_name=_("category"),
        on_delete=models.RESTRICT,
        db_index=True,
        related_name="articles",
    )
    main_image = models.ImageField(
        _("main image"),
        max_length=300,
        blank=True,
        null=True,
        upload_to="articles/images/%Y/%m",
    )
    is_featured = models.BooleanField(_("is featured"), default=False, db_index=True)
    title = models.CharField(_("title"), max_length=200)
    slug = AutoSlugField(
        populate_from="title", slugify_function=slugify, unique_for_date="published_at"
    )
    published_at = models.DateField(
        _("published at"), db_index=True, blank=True, null=True
    )
    short_content = models.TextField(_("short content"), max_length=600)
    content = models.TextField(_("content"))
    view_count = models.PositiveIntegerField(_("view count"), default=0, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = TaggableManager()
    objects = models.Manager()
    published = PublishedArticlesManager()
    main_image_thumbnail = ImageSpecField(
        source="main_image",
        processors=[ResizeToFill(450, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    main_image_medium = ImageSpecField(
        source="main_image",
        processors=[ResizeToFill(640, 480)],
        format="JPEG",
        options={"quality": 80},
    )

    class Meta:
        verbose_name = _("article")
        verbose_name_plural = _("articles")

    def __str__(self) -> str:
        return self.title

    def __repr__(self) -> str:
        return "<Article id={} title={} published_at={} created_at={}>".format(
            self.pk, self.title, self.published_at, self.created_at
        )

    @property
    def has_images(self):
        return self.images.count() > 0

    @property
    def comments_count(self):
        return self.comments.count()

    def get_comments(self):
        return self.comments.order_by("-created_at")

    def get_absolute_url(self):
        if self.published_at is None:
            return reverse("articles:list")
        return reverse(
            "articles:detail",
            kwargs={
                "slug": self.slug,
                "year": self.published_at.year,
                "month": self.published_at.month,
                "day": self.published_at.day,
            },
        )


class ArticleImage(models.Model):
    article = models.ForeignKey(
        Article,
        verbose_name=_("article"),
        on_delete=models.CASCADE,
        db_index=True,
        related_name="images",
    )
    title = models.CharField(_("title"), max_length=100, blank=True, null=True)
    image = models.ImageField(
        _("image"),
        max_length=300,
        upload_to="articles/images/%Y/%m",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image_thumbnail = ImageSpecField(
        source="image",
        processors=[ResizeToFill(450, 300)],
        format="JPEG",
        options={"quality": 80},
    )

    class Meta:
        verbose_name = _("article image")
        verbose_name_plural = _("article images")

    def __str__(self) -> str:
        return self.title if self.title else f"Article image #{self.pk}"

    def __repr__(self) -> str:
        return "<ArticleImage id={} article={} image={} created_at={}>".format(
            self.pk, self.article_id, self.image, self.created_at
        )

apps/articles/forms.py
from django import forms
from django_summernote.widgets import SummernoteInplaceWidget


class ArticleAdminForm(forms.ModelForm):
    content = forms.CharField(widget=SummernoteInplaceWidget())

apps/articles/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import F
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin, ProcessFormView
from taggit.models import Tag

from apps.comments.forms import CommentForm

from .models import Article, Category


class ArticleListView(ListView):
    queryset = Article.published.all()
    context_object_name = "articles"


class ArticleByCategoryListView(ListView):
    queryset = Article.published.all()
    context_object_name = "articles"

    def get_queryset(self):
        qs = super().get_queryset()

        category_slug = self.kwargs["slug"]
        qs = qs.filter(category__slug=category_slug)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["category"] = get_object_or_404(Category, slug=self.kwargs["slug"])

        return context


class ArticleByTagListView(ListView):
    queryset = Article.published.all()
    context_object_name = "articles"

    def get_queryset(self):
        qs = super().get_queryset()

        tag_slug = self.kwargs["slug"]
        qs = qs.filter(tags__slug=tag_slug)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["tag"] = get_object_or_404(Tag, slug=self.kwargs["slug"])

        return context


class ArticleDetailView(SuccessMessageMixin, FormMixin, DetailView, ProcessFormView):
    queryset = Article.objects.all()
    context_object_name = "article"
    form_class = CommentForm
    success_message = _("Thank you from your comment!")

    def increment_view_count(self):
        Article.objects.filter(
            slug=self.kwargs["slug"],
            published_at__year=self.kwargs["year"],
            published_at__month=self.kwargs["month"],
            published_at__day=self.kwargs["day"],
        ).update(view_count=F("view_count") + 1)

    def get(self, request, *args, **kwargs):
        # Not safe implementation
        # self.object.view_count += 1
        # self.object.save(update_fields=("view_count", "updated_at"))

        # Safer implementation (will increment on database level)
        self.increment_view_count()

        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None) -> "Article":
        if queryset is None:
            queryset = self.get_queryset()

        slug = self.kwargs["slug"]
        year = self.kwargs["year"]
        month = self.kwargs["month"]
        day = self.kwargs["day"]

        return queryset.get(
            slug=slug,
            published_at__year=year,
            published_at__month=month,
            published_at__day=day,
        )

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        return self.render_to_response(
            self.get_context_data(form=form, object=self.object)
        )

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.article = self.object
        form.save()

        return super().form_valid(form)

    def get_success_url(self) -> str:
        return self.object.get_absolute_url()

apps/articles/templates/articles/article_detail.html
{% extends 'base.html' %}
{% load i18n static %}
{% load django_bootstrap5 %}

{% block title %}{{ article.title }}{% endblock title %}

{% block extra_head %}
<style>
  .text-justify {
    text-align: justify;
  }
</style>
{% endblock extra_head %}

{% block extra_body %}
  <script src="{% static 'js/fslightbox.js' %}"></script>
{% endblock extra_body %}

{% block content %}
  <h1>{{ article.title }}</h1>

  <div class="mt-4 d-flex flex-row align-items-center gap-2">
    <h6 class="mb-0 text-primary">
      <a href="{{ article.category.get_absolute_url }}" class="text-decoration-none">
        {{ article.category.name }}</a>
    </h6>
    <time class="mb-0 text-muted h6">{{ article.published_at | date }}</time>

    {% if article.tags.count %}
      {% for tag in article.tags.all %}
        <a href="{% url 'articles:by-tag' tag.slug %}" class="mb-0 h6 text-secondary text-decoration-none">#{{ tag.name }}</a>
      {% endfor %}
    {% endif %}
  </div>

  <p class="mt-4 lead text-justify">
    {{ article.short_content }}
  </p>

  {% if article.main_image %}
    <div class="mt-4">
      <img
        class="img-thumbnail mx-auto d-block"
        src="{{ article.main_image_medium.url }}"
        alt="{{ article.title }}"
      />
    </div>
  {% endif %}

  <div class="mt-4 text-justify">
    {{ article.content | safe }}
  </div>

  {% if article.has_images %}
    <div class="mt-4 row row-cols-1 row-cols-md-3 row-cols-lg-4 gy-3">
      {% for article_image in article.images.all %}
        <div class="col">
          <a href="{{ article_image.image.url }}" data-fslightbox="images">
            <img
              class="img-fluid rounded"
              src="{{ article_image.image_thumbnail.url }}"
              alt="{{ article_image }}"
            />
          </a>
          <span>{{ article_image }}</span>
        </div>
      {% endfor %}
    </div>
  {% endif %}

  <section class="mt-5">
    <h3>{% trans "Comments" %} ({{ article.comments_count }})</h3>

    <hr />

    <div>
      {% if user.is_authenticated %}
        <div class="row">
          <div class="col-12 col-lg-6">
            <form method="post" class="form">
              {% csrf_token %}
              {% bootstrap_form form %}
              {% bootstrap_button button_type="submit" content="Add comment" %}
            </form>
          </div>
        </div>
      {% else %}
        <p class="text-center text-muted">
          {% trans "Please login or register to leave a comment" %}
        </p>
      {% endif %}
    </div>

    <div class="mt-4">
      {% for comment in article.get_comments %}
        <div class="mt-3 d-flex">
          <div class="flex-shrink-0">
            <img
              class="img-fluid rounded"
              width="80"
              src="{% static 'img/placeholder-user.jpg' %}"
              alt="{{ comment.user }}"
            />
          </div>
          <div class="flex-grow-1 ms-3">
            <p class="mb-1 text-muted">
              <strong>{{ comment.user_name }}</strong>
              <time>{{ comment.created_at | timesince }} ago</time>
            </p>
            <p>
              {{ comment.message }}
            </p>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>
{% endblock %}

apps/articles/templates/articles/article_list.html
{{% extends 'base.html' %}
{% load i18n %}
{% load articles_tags %}

{% block title %}{% trans "Articles" %}{% endblock title %}

{% block content %}
  <h1>
    {% trans "Articles" %}
    {% if category %}<small class="h3 text-muted">({{ category.name }})</small>{% endif %}
    {% if tag %}<small class="h3 text-muted">(#{{ tag.name }})</small>{% endif %}
  </h1>

  <div class="row">
    <div class="col-12 col-md-9">
      {% for article in articles %}
        <div class="my-4 row">
          <div class="col-3">
            {% if article.main_image %}
              <a href="{{ article.get_absolute_url }}">
                <img
                  class="img-thumbnail"
                  src="{{ article.main_image_thumbnail.url }}"
                  alt="{{ article.title }}"
                />
              </a>
            {% endif %}
          </div>
          <div class="col-9">
            <h3>
              <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
            </h3>
            <div class="mb-2 d-flex flex-row align-items-center gap-2">
              <h6 class="mb-0 text-primary">
                <a href="{{ article.category.get_absolute_url }}" class="text-decoration-none">
                  {{ article.category.name }}</a>
              </h6>
              <time class="mb-0 text-muted h6">{{ article.published_at | date }}</time>

              {% if article.tags.count %}
                {% for tag in article.tags.all %}
                  <a href="{% url 'articles:by-tag' tag.slug %}" class="mb-0 h6 text-secondary text-decoration-none">#{{ tag.name }}</a>
                {% endfor %}
              {% endif %}

              <p class="mb-0 h6 text-black-50 d-flex align-items-center">
                <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M10 12.5a2.5 2.5 0 100-5 2.5 2.5 0 000 5z" />
                  <path fill-rule="evenodd" d="M.664 10.59a1.651 1.651 0 010-1.186A10.004 10.004 0 0110 3c4.257 0 7.893 2.66 9.336 6.41.147.381.146.804 0 1.186A10.004 10.004 0 0110 17c-4.257 0-7.893-2.66-9.336-6.41zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd" />
                </svg>
                <span class="ms-1">{{ article.view_count | default:1 }}</span>
              </p>
            </div>
            <p>{{ article.short_content }}</p>
          </div>
        </div>

        {% if not forloop.last %}
          <hr class="border-top border-dark border-opacity-25" />
        {% endif %}
      {% endfor %}
    </div>

    <div class="col-12 col-md-3">
      {% render_categories_list %}

      <div class="mt-4">
        {% render_tags_cloud %}
      </div>
    </div>
  </div>
{% endblock content %}

apps/articles/templates/articles/articles_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Articles" %}{% endblock title %}

{% block content %}
  <h1>{% trans "Articles" %}</h1>

  {% for article in articles %}
    <div class="my-4 row">
      <div class="col-3">
        {% if article.main_image %}
          <img
            class="img-thumbnail"
            src="{{ article.main_image_thumbnail.url }}"
            alt="{{ article.title }}"
          />
        {% endif %}
      </div>
      <div class="col-9">
        <h3>{{ article.title }}</h3>
        <div class="mb-2 d-flex flex-row align-items-center gap-2">
          <h6 class="mb-0 text-primary">{{ article.category.name }}</h6>
          <time class="mb-0 text-muted h6">{{ article.published_at | date }}</time>

          {% if article.tags.count %}
            {% for tag in article.tags.all %}
              <span class="mb-0 h6">#{{ tag.name }}</span>
            {% endfor %}
          {% endif %}
        </div>
        <p>{{ article.short_content }}</p>
      </div>
    </div>

    {% if not forloop.last %}
      <hr class="border-top border-dark" />
    {% endif %}
  {% endfor %}
{% endblock content %}